version: "3.8"

services:
  mongodb:
    image: mongo:4.4.29
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - D:/mongoDB/mongodb4.4.29/data/db:/data/db
      

  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017/react-admin
    depends_on:
      - mongodb